import type { Metadata } from "next";
import "./globals.css";
import { Footer } from "@/components/footer";
import { ThemeProvider } from "@/components/theme-provider";
import { Header } from "@/components/header";

const metadata: Metadata = {
  title: "Barnvisor",
  description: "Generated by create next app",
};

export { metadata };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="antialiased">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="m-auto mx-auto grid max-w-screen-lg grid-cols-[192px_1fr_192px] gap-4 text-lg">
            <Header className="col-span-full" />
            <main className="col-span-full grid grid-cols-subgrid">
              {children}
            </main>
            <Footer className="col-span-full" />
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
